#####################################################################
# SoftDev Nord Docker Web Development Stack (SDN-WebDevDock) 1.0.0
#
# Runs Apache, MySQL, PHP, PhpMyAdmin and Redis
# SSL is preconfigured.
#
# APCu, ImageMagick, OPCache, Redis, and XDebug can be
# activated in the environment file.
#
# Run with
# docker-compose up -d
#
# (C)2022-2024 SoftDev Nord Rene Irrgang
#####################################################################

version: '3'

networks:
  icecat-service-net:
    ipam:
      config:
        - subnet: 172.200.0.0/16
          gateway: 172.200.0.1

services:

  #######################################
  # WebServer
  #######################################

  webserver:
    build: 
      context: ./.docker/${PHPVERSION}
      args:
        - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
    container_name: ${COMPOSE_PROJECT_NAME}-${PHPVERSION}
    hostname: ${COMPOSE_PROJECT_NAME}-c
    user: ${USER_ID}:${GROUP_ID}
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    domainname: ${APP_NAME}.local
    volumes: 
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${OPCACHE_INI}:/usr/local/etc/php/opcache.ini
      - ${XDEBUG_INI}:/usr/local/etc/php/xdebug.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-available
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
      - ${APACHE_CERTS_DIR-./config/certs}:/etc/apache2/ssl
      - /etc/localtime:/etc/localtime:ro
    environment:
      - APACHE_DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
      - PMA_PORT=${HOST_MACHINE_PMA_PORT}
    extra_hosts:
      -   "host.docker.internal:host-gateway"
    networks:
      icecat-service-net:
        ipv4_address: 172.200.0.2
